#!/bin/bash
f() {
	if [ -b "$1" ]; then
		echo "$1"
		exit 0
	fi
}
f "$1"
f "/dev/$1"
f "/dev/sd$1"
if [ -e "$1" ]; then
	A="$(df "$1" | tail -n1 | cut -f1 -d\ )"
	f "$A"
fi
echo "Failed to guess block device for '$1'"
exit 1
