#!/bin/dash

do_one() {
    local BD
    if BD="$(guessbd "$1")"; then
        echo Mounting "$BD"
        udisksctl mount -b "$BD"
    else
        echo Cannot mount "$1"
    fi
}

for s; do do_one "$s"; done
